# Generated by Django 4.1.7 on 2023-06-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ques',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
